# Generated by Django 4.1.5 on 2023-05-28 18:24

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BbCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('_bbcode_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('bbcode', precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, null=True, verbose_name='Содержание')),
            ],
        ),
    ]
