# Generated by Django 4.1.5 on 2023-05-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('icon_class', models.CharField(blank=True, max_length=255, verbose_name='Иконка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('icon_class', models.CharField(blank=True, max_length=255, verbose_name='Иконка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка на страницу')),
            ],
            options={
                'verbose_name': 'Меню Навигации',
                'verbose_name_plural': 'Меню Навигации',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('icon_class', models.CharField(blank=True, max_length=255, verbose_name='Иконка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='FooterAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок о нас')),
                ('text', models.TextField(blank=True, verbose_name='Текст о нас')),
                ('menu', models.ManyToManyField(blank=True, to='mainpage.menu', verbose_name='Меню')),
                ('social', models.ManyToManyField(blank=True, to='mainpage.social', verbose_name='Соц сети')),
            ],
        ),
    ]
